import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen grid grid-rows-[1, 1fr] bg-black`}
      >
        <nav className="bg-black border-b border-white text-white">
          <ul className="flex flex-row justify-around items-center my-5">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/champions"}>Champions</Link>
            </li>
            <li>
              <Link href={"/items"}>Items</Link>
            </li>
            <li>
              <Link href={"/rotation"}>Rotation</Link>
            </li>
          </ul>
        </nav>
        <div className="min-h-screen w-full flex justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
